language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements_26.txt --use-mirrors; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements.txt --use-mirrors; fi
# command to run tests
script: python setup.py -q nosetests
